### ISSUE TITLE
SNI support is missing (Was: SSL hostname mismatch)

### ISSUE THREAD

**Issue by 9mmtylenol** [tsyesika/Muon#7]
Using python2.7 since I'm getting `ImportError: No module named 'main'` errors, and when I input the webfinger `me@io.9mmtylenol.me` I get a ssl hostname mismatch. It's trying to request `www.9mmtylenol.me, 9mmtylenol.me` instead `io.9mmtylenol.me`. I believe this is an issue with python2.7 but that's the only version that will execute `src/muon`.

**Comment by tsyesika** [comment]
Muon isn't ready for use yet, I'll look into it though, thanks for reporting

**Comment by moggers87** [comment]
@xray7224 the cert on io.9mmtylenol.me is from StartSSL - if you remember we had similar issues with MegBot when MegWorld was using StartSSL certificates. This might be better off as a PyPump bug.

**Comment by moggers87** [comment]
Ignore my last comment - poking around with OpenSSL it seems @9mmtylenol is proxying behind nginx and relying on SNI. Changing bug title to reflect this.

**Comment by moggers87** [comment]
This bug was already reported in PyPump and needs to be fixed there

Closing this now, feel free to comment on xray7224/PyPump#43 if you have anything to add :)
