### ISSUE TITLE
AttributeError: 'PyPump' object has no attribute 'Http://openfarmgame.com/schema/object-type/crop'.

### ISSUE THREAD

**Issue by ryanweal** [tsyesika/Muon#8]
Hello! I just tried running this for the first time and this is the error I'm getting. After pressing any key the message goes away and I can usually see a few inbox items. Sometimes only one, sometimes zero, sometimes 5... once I get past this screen though I can't do anything besides quit the application.

![image](https://f.cloud.github.com/assets/3308817/1470848/565f2742-45ca-11e3-9b89-c9df7356858e.png)

**Comment by ryanweal** [comment]
Let me know if I should post this over at PyPump...

**Comment by moggers87** [comment]
Yeah, pretty sure this is PyPump bug. You can try and reproduce this bug with PyPump's shell

**Comment by tsyesika** [comment]
Yep this is a PyPump bug.

**Comment by moggers87** [comment]
I'll close this bug then :P
